title: Sharing His Love

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post" # This ensures that you don't have to put this in the frontmatter of every single post.
      is_post: true # automatically set is_post=true for all posts (used to determine in which header to show at the top of each page)
      author: "Riley" # Riley is the main author, but this can be overridden in a post's frontmatter.
  - scope:
      path: ""
    values:
      layout: "default"

# Other variables
# Tags (This tells Jekyll to generate a new directory called tag and place tag pages in that directory.)
# tag_page_dir: tag
timezone: America/Denver
